/* Close Open Modal */
export const OPEN_CART = "OPEN_CART";
export const CLOSE_CART = "CLOSE_CART";
export const OPEN_MENU_MOBILE = "OPEN_MENU_MOBILE";
export const CLOSE_MENU_MOBILE = "CLOSE_MENU_MOBILE";
export const OPEN_SEARCH = "OPEN_SEARCH";
export const CLOSE_SEARCH = "CLOSE_SEARCH";
export const OPEN_PRODUCT_MODAL = "OPEN_PRODUCT_MODAL";
export const CLOSE_PRODUCT_MODAL = "CLOSE_PRODUCT_MODAL";
export const OPEN_MESSAGE = "OPEN_MESSAGE";
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";

/* Required Size */
export const ON_REQUIRED_SIZE = "ON_REQUIRED_SIZE";
export const OFF_REQUIRED_SIZE = "OFF_REQUIRED_SIZE";

/*  */
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const VIEW_PRODUCT_DETAIL = "VIEW_PRODUCT_DETAIL";
export const QUICK_VIEW_PRODUCT = "QUICK_VIEW_PRODUCT";

/*  */
export const FETCH_PRODUCTS_IN_CART = "FETCH_PRODUCTS_IN_CART";
export const ADD_PRODUCT_TO_CARD = "ADD_PRODUCT_TO_CARD";
export const UPDATE_PRODUCT_TO_CART = "UPDATE_PRODUCT_TO_CART";
